---
- name: Garantindo configuração para Debian
  block:
    - name: Importando chave
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
    - name: Garantindo repositorio
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/oss-7.x/apt stable main
        state: present
        filename: elastic-7
        update_cache: yes

  when: ansible_os_family|lower == 'debian'

- name: Garantindo configuração para Centos
  block:
    - name: Importando chave
      shell: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

    - name: Garantindo repositorio
      yum_repository: 
        name: elasticsearch
        baseurl: https://artifacts.elastic.co/packages/oss-7.x/yum
        gpgcheck: yes
        description: "Repositorio do elastic 7"
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch

  when: ansible_os_family|lower == 'redhat'

- name: Garantindo instalação do pacote ES
  package:
    name: elasticsearch-oss
