---
- hosts: all
  tasks:
    - name: Garantindo Elasticsearch
      block:
        - name: Importando chave do ES e Garantindo repo [Debian]
          ansible.builtin.shell: |
            wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-7.x.list
            apt update
          when: ansible_distribution|lower == 'ubuntu'

#        - name: Importando repositorio [Debian]
#          ansible.builtin.shell: echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-7.x.list
#          when: ansible_distribution|lower = 'ubuntu'


        - name: Importando chave do ES [CentOS]
          ansible.builtin.shell: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
          when: ansible_distribution|lower == 'centos'

        - name: Garantindo repositorio [CentOS]
          ansible.builtin.blockinfile:
            path: /etc/yum.repos.d/elasticsearch.repo
            block: |
              [elasticsearch]
              name=Elasticsearch repository for 7.x packages
              baseurl=https://artifacts.elastic.co/packages/7.x/yum
              gpgcheck=1
              gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
              enabled=0
              autorefresh=1
              type=rpm-md
            create: yes
          when: ansible_distribution|lower == 'centos'

        - name: Garantindo instalação do pacote ES
          ansible.builtin.package:
            name: elasticsearch

        - name: Habitando serviço
          ansible.builtin.service:
            name: elasticsearch
            state: started
            enabled: yes
