---
- hosts: all 
  become: yes 
  vars:
    graylog_root_password_sha2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
    graylog_password_secret: "2jueVqZpwLLjaWxV"
    graylog_bind_address: "0.0.0.0:9000"
  roles:
    - graylog_stack
